version: '3'

services:
  app:
    build:
      context: ./CRUD
      dockerfile: Dockerfile
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: db:3306/laboratorio
      DB_USER_NAME: root
      DB_PASSWORD: 12345678
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: laboratorio
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  frontend:
    build:
      context: ./front_crud
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://app:8080
    depends_on:
      - app
    restart: always